import { useLocalStorage } from "usehooks-ts";

export const languages = [
	{ value: "en", label: "English", flag: "🇺🇸" },
	{ value: "es", label: "Español", flag: "🇪🇸" },
	{ value: "fr", label: "Français", flag: "🇫🇷" },
	{ value: "de", label: "Deutsch", flag: "🇩🇪" },
	{ value: "zh", label: "中文", flag: "🇨🇳" },
	{ value: "ja", label: "日本語", flag: "🇯🇵" },
] as const;

export type Language = (typeof languages)[number]["value"];

export function useTranslations() {
	const [lang] = useLocalStorage<{ language: Language }>(
		"lang",
		{ language: "en" },
		{ initializeWithValue: true },
	);

	return textContent[lang.language];
}

export const textContent = {
	en: {
		common: {
			loading: "Loading...",
			cancel: "Cancel",
			create: "Create",
			search: "Search",
			name: "Name",
			description: "Description",
			error: "Error",
			success: "Success",
			send: "Send",
			back: "Go Back",
			home: "Home",
			tryAgain: "Try Again",
			signOut: "Sign out",
			login: "Login",
			dark: "Dark",
			light: "Light",
			new: "New",
			chat: "Chat",
			conversation: "Conversation",
			message: "Message",
			messages: "Messages",
			user: "user",
			users: "users",
			selected: "selected",
			original: "Original",
			sending: "Sending...",
			mediaSharingComingSoon: "Media sharing coming soon!",
			sendMessage: "Send message",
			typeYourMessage: "Type your message...",
		},
		index: {
			title: "Break Language Barriers with Instant Chat",
			description:
				"Chat naturally in any language. Our AI-powered translation lets you connect with anyone, anywhere, instantly. Select your preferred language to begin.",
			chooseLanguage: "Choose your preferred language",
			languageDescription:
				"This will be your default language for chatting and translations",
			getStarted: "Get Started",
			english: "English",
		},
		app: {
			loadingMore: "Loading more...",
			readyToConnect: "Ready to Connect?",
			startFirstConversation:
				"Start your first conversation by creating a new chat with friends or groups",
			startConversation: "Start your first conversation",
			newChat: "New Chat",
			newChatAria: "New chat",
			conversationStartsHere: "Conversation starts here",
			breakIceMessage:
				"Break the ice! Send your first message to begin chatting.",
		},
		auth: {
			authenticationRequired: "Authentication Required",
			mustBeSignedIn: "You must be signed in to access this content.",
		},
		notFound: {
			pageNotFound: "Oops! The page you're looking for doesn't exist.",
			takeMeHome: "Take Me Home",
		},
		newChat: {
			createNewConversation: "Create New Conversation",
			chooseWhoToChat:
				"Choose who you'd like to chat with - individuals or groups",
			conversationName: "Conversation Name",
			conversationNamePlaceholder: "e.g., Weekend Plans",
			conversationNameDescription:
				"Choose a memorable name for this conversation",
			addParticipants: "Add Participants",
			searchUsers: "Search users...",
			selectAtLeastOneUser: "Select at least one user",
			nameBetween2And100: "Name must be between 2 and 100 characters",
			creatingConversation: "Creating your conversation...",
			createChat: "Create Chat",
		},
		seo: {
			title: "Chat - Connect Across Languages",
			description:
				"Real-time chat with instant translation. Connect with people worldwide in their native language.",
		},
	},
	es: {
		common: {
			loading: "Cargando...",
			cancel: "Cancelar",
			create: "Crear",
			search: "Buscar",
			name: "Nombre",
			description: "Descripción",
			error: "Error",
			success: "Éxito",
			send: "Enviar",
			back: "Volver",
			home: "Inicio",
			tryAgain: "Intentar de nuevo",
			signOut: "Cerrar sesión",
			login: "Iniciar sesión",
			dark: "Oscuro",
			light: "Claro",
			new: "Nuevo",
			chat: "Chat",
			conversation: "Conversación",
			message: "Mensaje",
			messages: "Mensajes",
			user: "usuario",
			users: "usuarios",
			selected: "seleccionado",
			original: "Original",
			sending: "Enviando...",
			mediaSharingComingSoon: "¡Compartición de medios próximamente!",
			sendMessage: "Enviar mensaje",
			typeYourMessage: "Escribe tu mensaje...",
		},
		index: {
			title: "Rompe las Barreras del Idioma con Chat Instantáneo",
			description:
				"Chatea naturalmente en cualquier idioma. Nuestra traducción impulsada por IA te permite conectarte con cualquiera, en cualquier lugar, al instante. Selecciona tu idioma preferido para comenzar.",
			chooseLanguage: "Elige tu idioma preferido",
			languageDescription:
				"Este será tu idioma predeterminado para chatear y traducciones",
			getStarted: "Comenzar",
			english: "Inglés",
		},
		app: {
			loadingMore: "Cargando más...",
			readyToConnect: "¿Listo para Conectar?",
			startFirstConversation:
				"Comienza tu primera conversación creando un nuevo chat con amigos o grupos",
			startConversation: "Comienza tu primera conversación",
			newChat: "Nuevo Chat",
			newChatAria: "Nuevo chat",
			conversationStartsHere: "La conversación comienza aquí",
			breakIceMessage:
				"¡Rompe el hielo! Envía tu primer mensaje para comenzar a chatear.",
		},
		auth: {
			authenticationRequired: "Autenticación Requerida",
			mustBeSignedIn: "Debes iniciar sesión para acceder a este contenido.",
		},
		notFound: {
			pageNotFound: "¡Ups! La página que buscas no existe.",
			takeMeHome: "Llévame a casa",
		},
		newChat: {
			createNewConversation: "Crear Nueva Conversación",
			chooseWhoToChat: "Elige con quién quieres chatear - individuos o grupos",
			conversationName: "Nombre de la Conversación",
			conversationNamePlaceholder: "ej. Planes de fin de semana",
			conversationNameDescription:
				"Elige un nombre memorable para esta conversación",
			addParticipants: "Agregar Participantes",
			searchUsers: "Buscar usuarios...",
			selectAtLeastOneUser: "Selecciona al menos un usuario",
			nameBetween2And100: "El nombre debe tener entre 2 y 100 caracteres",
			creatingConversation: "Creando tu conversación...",
			createChat: "Crear Chat",
		},
		seo: {
			title: "Chat - Conecta a Través de Idiomas",
			description:
				"Chat en tiempo real con traducción instantánea. Conecta con personas de todo el mundo en su idioma nativo.",
		},
	},
	fr: {
		common: {
			loading: "Chargement...",
			cancel: "Annuler",
			create: "Créer",
			search: "Rechercher",
			name: "Nom",
			description: "Description",
			error: "Erreur",
			success: "Succès",
			send: "Envoyer",
			back: "Retour",
			home: "Accueil",
			tryAgain: "Réessayer",
			signOut: "Se déconnecter",
			login: "Se connecter",
			dark: "Sombre",
			light: "Clair",
			new: "Nouveau",
			chat: "Chat",
			conversation: "Conversation",
			message: "Message",
			messages: "Messages",
			user: "utilisateur",
			users: "utilisateurs",
			selected: "sélectionné",
			original: "Original",
			sending: "Envoi en cours...",
			mediaSharingComingSoon: "Partage de médias bientôt disponible !",
			sendMessage: "Envoyer le message",
			typeYourMessage: "Tapez votre message...",
		},
		index: {
			title: "Brisez les Barrières Linguistiques avec le Chat Instantané",
			description:
				"Discutez naturellement dans n'importe quelle langue. Notre traduction alimentée par l'IA vous permet de vous connecter avec n'importe qui, n'importe où, instantanément. Sélectionnez votre langue préférée pour commencer.",
			chooseLanguage: "Choisissez votre langue préférée",
			languageDescription:
				"Ce sera votre langue par défaut pour discuter et les traductions",
			getStarted: "Commencer",
			english: "Anglais",
		},
		app: {
			loadingMore: "Charger plus...",
			readyToConnect: "Prêt à vous Connecter ?",
			startFirstConversation:
				"Commencez votre première conversation en créant un nouveau chat avec des amis ou des groupes",
			startConversation: "Commencez votre première conversation",
			newChat: "Nouveau Chat",
			newChatAria: "Nouveau chat",
			conversationStartsHere: "La conversation commence ici",
			breakIceMessage:
				"Brisez la glace ! Envoyez votre premier message pour commencer à discuter.",
		},
		auth: {
			authenticationRequired: "Authentification Requise",
			mustBeSignedIn: "Vous devez être connecté pour accéder à ce contenu.",
		},
		notFound: {
			pageNotFound: "Oups ! La page que vous recherchez n'existe pas.",
			takeMeHome: "Ramenez-moi à la maison",
		},
		newChat: {
			createNewConversation: "Créer une Nouvelle Conversation",
			chooseWhoToChat:
				"Choisissez avec qui vous voulez discuter - individus ou groupes",
			conversationName: "Nom de la Conversation",
			conversationNamePlaceholder: "ex. Plans du week-end",
			conversationNameDescription:
				"Choisissez un nom mémorable pour cette conversation",
			addParticipants: "Ajouter des Participants",
			searchUsers: "Rechercher des utilisateurs...",
			selectAtLeastOneUser: "Sélectionnez au moins un utilisateur",
			nameBetween2And100: "Le nom doit contenir entre 2 et 100 caractères",
			creatingConversation: "Création de votre conversation...",
			createChat: "Créer un Chat",
		},
		seo: {
			title: "Chat - Se Connecter à Travers les Langues",
			description:
				"Chat en temps réel avec traduction instantanée. Connectez-vous avec des personnes du monde entier dans leur langue native.",
		},
	},
	de: {
		common: {
			loading: "Laden...",
			cancel: "Abbrechen",
			create: "Erstellen",
			search: "Suchen",
			name: "Name",
			description: "Beschreibung",
			error: "Fehler",
			success: "Erfolg",
			send: "Senden",
			back: "Zurück",
			home: "Startseite",
			tryAgain: "Erneut versuchen",
			signOut: "Abmelden",
			login: "Anmelden",
			dark: "Dunkel",
			light: "Hell",
			new: "Neu",
			chat: "Chat",
			conversation: "Unterhaltung",
			message: "Nachricht",
			messages: "Nachrichten",
			user: "Benutzer",
			users: "Benutzer",
			selected: "ausgewählt",
			original: "Original",
			sending: "Wird gesendet...",
			mediaSharingComingSoon: "Medienaustausch kommt bald!",
			sendMessage: "Nachricht senden",
			typeYourMessage: "Geben Sie Ihre Nachricht ein...",
		},
		index: {
			title: "Sprachbarrieren mit Sofort-Chat durchbrechen",
			description:
				"Chatten Sie natürlich in jeder Sprache. Unsere KI-gestützte Übersetzung ermöglicht es Ihnen, sich mit jedem, überall, sofort zu verbinden. Wählen Sie Ihre bevorzugte Sprache, um zu beginnen.",
			chooseLanguage: "Wählen Sie Ihre bevorzugte Sprache",
			languageDescription:
				"Dies wird Ihre Standardsprache für Chats und Übersetzungen sein",
			getStarted: "Loslegen",
			english: "Englisch",
		},
		app: {
			loadingMore: "Mehr laden...",
			readyToConnect: "Bereit zum Verbinden?",
			startFirstConversation:
				"Beginnen Sie Ihre erste Unterhaltung, indem Sie einen neuen Chat mit Freunden oder Gruppen erstellen",
			startConversation: "Beginnen Sie Ihre erste Unterhaltung",
			newChat: "Neuer Chat",
			newChatAria: "Neuer Chat",
			conversationStartsHere: "Die Unterhaltung beginnt hier",
			breakIceMessage:
				"Brechen Sie das Eis! Senden Sie Ihre erste Nachricht, um zu chatten.",
		},
		auth: {
			authenticationRequired: "Authentifizierung Erforderlich",
			mustBeSignedIn:
				"Sie müssen angemeldet sein, um auf diesen Inhalt zuzugreifen.",
		},
		notFound: {
			pageNotFound: "Ups! Die Seite, die Sie suchen, existiert nicht.",
			takeMeHome: "Bring mich nach Hause",
		},
		newChat: {
			createNewConversation: "Neue Unterhaltung Erstellen",
			chooseWhoToChat:
				"Wählen Sie aus, mit wem Sie chatten möchten - Einzelpersonen oder Gruppen",
			conversationName: "Name der Unterhaltung",
			conversationNamePlaceholder: "z.B. Wochenendpläne",
			conversationNameDescription:
				"Wählen Sie einen einprägsamen Namen für diese Unterhaltung",
			addParticipants: "Teilnehmer Hinzufügen",
			searchUsers: "Benutzer suchen...",
			selectAtLeastOneUser: "Wählen Sie mindestens einen Benutzer aus",
			nameBetween2And100: "Der Name muss zwischen 2 und 100 Zeichen lang sein",
			creatingConversation: "Ihre Unterhaltung wird erstellt...",
			createChat: "Chat Erstellen",
		},
		seo: {
			title: "Chat - Über Sprachen Verbinden",
			description:
				"Echtzeit-Chat mit sofortiger Übersetzung. Verbinden Sie sich mit Menschen weltweit in ihrer Muttersprache.",
		},
	},
	zh: {
		common: {
			loading: "加载中...",
			cancel: "取消",
			create: "创建",
			search: "搜索",
			name: "名称",
			description: "描述",
			error: "错误",
			success: "成功",
			send: "发送",
			back: "返回",
			home: "首页",
			tryAgain: "重试",
			signOut: "退出登录",
			login: "登录",
			dark: "深色",
			light: "浅色",
			new: "新建",
			chat: "聊天",
			conversation: "对话",
			message: "消息",
			messages: "消息",
			user: "用户",
			users: "用户",
			selected: "已选择",
			original: "原文",
			sending: "发送中...",
			mediaSharingComingSoon: "媒体分享即将推出！",
			sendMessage: "发送消息",
			typeYourMessage: "输入您的消息...",
		},
		index: {
			title: "用即时聊天打破语言障碍",
			description:
				"用任何语言自然聊天。我们的人工智能驱动翻译让您可以与任何人、任何地方即时连接。选择您的首选语言开始。",
			chooseLanguage: "选择您的首选语言",
			languageDescription: "这将是您聊天和翻译的默认语言",
			getStarted: "开始使用",
			english: "英语",
		},
		app: {
			loadingMore: "加载更多...",
			readyToConnect: "准备连接？",
			startFirstConversation: "通过与朋友或群组创建新聊天开始您的第一次对话",
			startConversation: "开始您的第一次对话",
			newChat: "新聊天",
			newChatAria: "新聊天",
			conversationStartsHere: "对话从这里开始",
			breakIceMessage: "打破僵局！发送您的第一条消息开始聊天。",
		},
		auth: {
			authenticationRequired: "需要认证",
			mustBeSignedIn: "您必须登录才能访问此内容。",
		},
		notFound: {
			pageNotFound: "哎呀！您查找的页面不存在。",
			takeMeHome: "带我回家",
		},
		newChat: {
			createNewConversation: "创建新对话",
			chooseWhoToChat: "选择您想与之聊天的人 - 个人或群组",
			conversationName: "对话名称",
			conversationNamePlaceholder: "例如，周末计划",
			conversationNameDescription: "为此次对话选择一个容易记住的名称",
			addParticipants: "添加参与者",
			searchUsers: "搜索用户...",
			selectAtLeastOneUser: "至少选择一个用户",
			nameBetween2And100: "名称必须介于2到100个字符之间",
			creatingConversation: "正在创建您的对话...",
			createChat: "创建聊天",
		},
		seo: {
			title: "聊天 - 跨越语言连接",
			description: "实时聊天与即时翻译。与世界各地的人们用他们的母语连接。",
		},
	},
	ja: {
		common: {
			loading: "読み込み中...",
			cancel: "キャンセル",
			create: "作成",
			search: "検索",
			name: "名前",
			description: "説明",
			error: "エラー",
			success: "成功",
			send: "送信",
			back: "戻る",
			home: "ホーム",
			tryAgain: "再試行",
			signOut: "サインアウト",
			login: "ログイン",
			dark: "ダーク",
			light: "ライト",
			new: "新規",
			chat: "チャット",
			conversation: "会話",
			message: "メッセージ",
			messages: "メッセージ",
			user: "ユーザー",
			users: "ユーザー",
			selected: "選択済み",
			original: "原文",
			sending: "送信中...",
			mediaSharingComingSoon: "メディア共有は近日公開！",
			sendMessage: "メッセージを送信",
			typeYourMessage: "メッセージを入力...",
		},
		index: {
			title: "インスタントチャットで言語の壁を破る",
			description:
				"あらゆる言語で自然にチャット。AIを活用した翻訳により、誰とでも、どこでも、即座に接続できます。お好みの言語を選択して開始してください。",
			chooseLanguage: "お好みの言語を選択",
			languageDescription: "これはチャットと翻訳のデフォルト言語になります",
			getStarted: "開始",
			english: "英語",
		},
		app: {
			loadingMore: "さらに読み込み中...",
			readyToConnect: "接続の準備はできましたか？",
			startFirstConversation:
				"友人やグループとの新しいチャットを作成して、最初の会話を開始してください",
			startConversation: "最初の会話を開始",
			newChat: "新規チャット",
			newChatAria: "新規チャット",
			conversationStartsHere: "会話はここから始まります",
			breakIceMessage:
				"氷を破ってください！最初のメッセージを送ってチャットを始めましょう。",
		},
		auth: {
			authenticationRequired: "認証が必要です",
			mustBeSignedIn: "このコンテンツにアクセスするにはログインが必要です。",
		},
		notFound: {
			pageNotFound: "おっと！お探しのページは存在しません。",
			takeMeHome: "ホームへ戻る",
		},
		newChat: {
			createNewConversation: "新しい会話を作成",
			chooseWhoToChat:
				"誰とチャットするか選択してください - 個人またはグループ",
			conversationName: "会話名",
			conversationNamePlaceholder: "例: 週末の予定",
			conversationNameDescription: "この会話の覚えやすい名前を選択してください",
			addParticipants: "参加者を追加",
			searchUsers: "ユーザーを検索...",
			selectAtLeastOneUser: "少なくとも1人のユーザーを選択してください",
			nameBetween2And100: "名前は2〜100文字である必要があります",
			creatingConversation: "会話を作成中...",
			createChat: "チャットを作成",
		},
		seo: {
			title: "チャット - 言語を越えてつながる",
			description:
				"リアルタイムチャットと即時翻訳。世界中の人々と彼らの母語でつながります。",
		},
	},
};
